### ISSUE TITLE
massdata

### ISSUE THREAD

**Issue by kaizadp** [PNNL-TES/TES-drydown#1]
https://github.com/PNNL-TES/TES-drydown/blob/62e594727ea7a8c6fb3d1b1236268d4d5e7038b3/README.Rmd#L27

@bpbond 
We are pulling in data from the drake_plan.R file, correct? 
I can't go beyond this, because it can't find the file.

**Comment by kaizadp** [comment]
https://github.com/PNNL-TES/TES-drydown/blob/62e594727ea7a8c6fb3d1b1236268d4d5e7038b3/drake_plan.R#L30

I'm guessing this is where we create the _massdata_ file? But I'm not sure what's going on here.

**Comment by bpbond** [comment]
Hi @kaizadp - have you tried (i) cloning the entire repository and then (ii) source'ing `drake_plan.R`? (You will need to install a few packages, listed at the top, for it to work.)

`massdata` is a data object that's downloaded from Sarah's google sheet, not a file, which is why you can't find it.

**Comment by kaizadp** [comment]
I added `source("drake_plan.R")` to `Readme.Rmd`

Got this error:

> Quitting from lines 27-41 (README.Rmd) 
> Error: key 'massdata' ('objects') not found
> Execution halted

**Comment by bpbond** [comment]
Ah, okay. Sorry–this isn't really documented, because this repo is still rudimentary and I wasn't expecting anyone else to try to run this.

1. Remove any modifications to `drake_plan.R`
2. `source()` the `drake_plan.R` file
3. Type `make(plan)` at the command line

This orders [drake](https://ropensci.github.io/drake) to build ('make') the plan, which is to (i) download the mass data, line 31; (ii) read the mass data into memory, 32; and (iii) generate a new report, lines 34-38.

**Comment by kaizadp** [comment]
Success! Thanks
